# shellcheck shell=bash

#######################################
# Resolves the path to the plugins manifest file (installed plugins list).
# Search priority:
#   1. $SHELLX_PLUGINS_MANIFEST environment variable
#   2. ~/.shellx.plugins (default)
# Globals:
#   SHELLX_PLUGINS_MANIFEST - Optional override path.
# Outputs:
#   Writes the resolved manifest file path to stdout.
#######################################
shellx::plugins::manifest::path() {
  if [ -n "${SHELLX_PLUGINS_MANIFEST}" ]; then
    echo "${SHELLX_PLUGINS_MANIFEST}"
    return 0
  fi

  echo "${HOME}/.shellx.plugins"
}

#######################################
# Saves (adds or updates) a plugin entry in the manifest file.
# Creates the manifest file and parent directory if they do not exist.
# If an entry for the same URL already exists, it is replaced (idempotent).
# Arguments:
#   $1 - URL of the plugin repository.
#   $2 - (Optional) Git ref (branch, tag, commit) to pin.
# Returns:
#   0 on success, 1 on failure.
#######################################
shellx::plugins::manifest::save() {
  local url="${1}"
  local ref="${2:-}"
  local manifest_file

  manifest_file=$(shellx::plugins::manifest::path)

  mkdir -p "$(dirname "${manifest_file}")"

  if [ ! -f "${manifest_file}" ]; then
    printf "# ShellX Plugins Manifest\n" > "${manifest_file}"
    printf "# Format: URL | REF  (REF is optional: branch, tag, or commit)\n" >> "${manifest_file}"
    printf "#\n" >> "${manifest_file}"
  fi

  # Remove any existing line for this URL, then append the (updated) entry
  local tmpfile
  tmpfile="$(mktemp)"
  grep -v "^[[:space:]]*${url}" "${manifest_file}" > "${tmpfile}" \
    && mv "${tmpfile}" "${manifest_file}" \
    || rm -f "${tmpfile}"

  if [ -n "${ref}" ]; then
    printf "%s | %s\n" "${url}" "${ref}" >> "${manifest_file}"
  else
    printf "%s\n" "${url}" >> "${manifest_file}"
  fi
}

#######################################
# Removes a plugin entry from the manifest file.
# Matches by plugin name (the basename of the repository URL).
# Arguments:
#   $1 - Plugin name (basename of the URL, without .git suffix).
# Returns:
#   0 on success or when no entry exists.
#######################################
shellx::plugins::manifest::remove() {
  local name="${1}"
  local manifest_file

  manifest_file=$(shellx::plugins::manifest::path)

  if [ ! -f "${manifest_file}" ]; then
    return 0
  fi

  local tmpfile
  tmpfile="$(mktemp)"
  # Match any line whose URL path ends with /<name> or /<name>.git
  grep -Ev "[/]${name}(\.git)?([[:space:]]*\|.*)?$" "${manifest_file}" > "${tmpfile}" \
    && mv "${tmpfile}" "${manifest_file}" \
    || rm -f "${tmpfile}"
}

#######################################
# Prints a manifest-formatted list of all user-installed git-backed plugins.
# Scans $__shellx_plugins_d for subdirectories that are git repositories,
# resolves each one's remote URL and current branch, and writes lines in the
# manifest format so the output can be redirected straight to ~/.shellx.plugins.
#
# Example usage:
#   shellx plugins export > ~/.shellx.plugins
#
# Globals:
#   __shellx_plugins_d - Base directory for user-installed plugins.
# Outputs:
#   Writes manifest lines to stdout (plain text, no colour codes).
# Returns:
#   0 always.
#######################################
shellx::plugins::export() {
  # shellcheck disable=SC2154
  local plugins_dir="${__shellx_plugins_d}"

  printf "# ShellX Plugins Manifest\n"
  printf "# Format: URL | REF  (REF is optional: branch, tag, or commit)\n"
  printf "# Generated by: shellx plugins export\n"
  printf "#\n"

  if [ ! -d "${plugins_dir}" ]; then
    return 0
  fi

  local entry url ref
  for entry in "${plugins_dir}"/*/; do
    # Skip if glob expanded to a literal (empty dir)
    [ -d "${entry}" ] || continue
    # Only consider git-backed plugins
    [ -d "${entry}/.git" ] || continue

    url=$(git -C "${entry}" remote get-url origin 2>/dev/null || true)
    [ -z "${url}" ] && continue

    ref=$(git -C "${entry}" symbolic-ref --short HEAD 2>/dev/null \
          || git -C "${entry}" rev-parse --short HEAD 2>/dev/null \
          || true)

    if [ -n "${ref}" ]; then
      printf "%s | %s\n" "${url}" "${ref}"
    else
      printf "%s\n" "${url}"
    fi
  done
}

#######################################
# Reads the manifest file and installs every listed plugin that is not yet
# present. Already-installed plugins are skipped without error.
# Respects the pinned git ref (branch/tag/commit) recorded in the manifest.
# Returns:
#   0 when all entries are processed.
#   1 if the manifest file does not exist.
#######################################
shellx::plugins::sync() {
  local manifest_file
  manifest_file=$(shellx::plugins::manifest::path)

  if [ ! -f "${manifest_file}" ]; then
    echo "[PLUGIN] Manifest not found: ${manifest_file}"
    echo "[PLUGIN] Install plugins with 'shellx plugins install <url>' to populate it."
    return 1
  fi

  local count=0
  local installed_count=0
  local skipped_count=0

  while IFS='|' read -r url ref || [ -n "${url}" ]; do
    # Skip comment lines and blank lines
    [[ "${url}" =~ ^[[:space:]]*# ]] && continue
    [[ -z "${url//[[:space:]]/}" ]] && continue

    # Trim surrounding whitespace
    url="${url#"${url%%[![:space:]]*}"}"
    url="${url%"${url##*[![:space:]]}"}"
    ref="${ref#"${ref%%[![:space:]]*}"}"
    ref="${ref%"${ref##*[![:space:]]}"}"

    count=$((count + 1))

    local plugin_name
    plugin_name=$(basename "${url}" .git)

    if shellx::plugins::is_installed "${plugin_name}"; then
      echo "[PLUGIN] ${plugin_name} already installed, skipping."
      skipped_count=$((skipped_count + 1))
    else
      # Pass ref only when non-empty to avoid passing an empty --branch arg
      if [ -n "${ref}" ]; then
        shellx::plugins::install "${url}" "${ref}"
      else
        shellx::plugins::install "${url}"
      fi
      installed_count=$((installed_count + 1))
    fi
  done < "${manifest_file}"

  echo "[PLUGIN] Sync complete: ${count} listed, ${installed_count} installed, ${skipped_count} skipped."
}
