name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: azohra/shell-linter@latest
        with:
          exclude-paths: "plugin-examples,hack"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Test ShellX bootstrap
        run: source shellx.sh
      - name: Test ShellX cli
        env:
          SHELLX_DEBUG: yes
        run: |
          source shellx.sh
          shellx version
          shellx info
      - name: Test ShellX Plugins Management
        env:
          SHELLX_DEBUG: yes
        run: |
          source shellx.sh

          echo "Installing community plugins"
          shellx plugins install https://github.com/0ghny/shellx-community-plugins
          shellx plugins installed
          shellx plugins is_installed shellx-community-plugins

          echo "Uninstalling community plugins"
          shellx plugins uninstall shellx-community-plugins
          shellx plugins is_installed shellx-community-plugins && exit 1
