name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: azohra/shell-linter@latest
        with:
          path: "shellx.sh,lib/core/*.sh,lib/shellx/*.sh,plugins/*.sh"
          exclude-paths: "plugin-examples,hack"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Test ShellX bootstrap
        env:
          SHELLX_DEBUG: yes
          SHELLX_HOME: ${{ github.workspace }}
        run: source shellx.sh
      - name: Test ShellX cli
        env:
          SHELLX_DEBUG: yes
          SHELLX_HOME: ${{ github.workspace }}
        run: |
          # https://github.com/actions/toolkit/issues/766
          echo "Enabling aliases definition"
          shopt -s expand_aliases

          echo "Bootstrapping shellx"
          source shellx.sh

          echo "Checking shellx version command"
          shellx version

          echo "Checking shellx info command"
          shellx info
      - name: Test ShellX Plugins Management
        env:
          SHELLX_DEBUG: yes
          SHELLX_HOME: ${{ github.workspace }}
        run: |
          # https://github.com/actions/toolkit/issues/766
          echo "Enabling aliases definition"
          shopt -s expand_aliases

          echo "Bootstrapping shellx"
          source shellx.sh

          echo "Installing community plugins"
          shellx plugins install https://github.com/0ghny/shellx-community-plugins
          shellx plugins installed
          shellx plugins is_installed shellx-community-plugins
          echo "Printing shellx.plugins.dir content"
          ls -lah ${__shellx_plugins_d}

          echo "Uninstalling community plugins"
          shellx plugins uninstall shellx-community-plugins
          ls -lah ${__shellx_plugins_d}
          shellx plugins is_installed shellx-community-plugins && exit 1
