name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: azohra/shell-linter@latest
        with:
          path: "shellx.sh,lib/core/*.sh,lib/shellx/*.sh,plugins/*.sh"
          exclude-paths: "plugin-examples,hack"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.9.0

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Unit Tests
        run: bats -r .

      - name: Test ShellX bootstrap
        env:
          SHELLX_DEBUG: yes
          SHELLX_HOME: ${{ github.workspace }}
        run: source shellx.sh

      - name: e2e ShellX cli
        env:
          SHELLX_DEBUG: yes
          SHELLX_HOME: ${{ github.workspace }}
        run: |
          # https://github.com/actions/toolkit/issues/766
          echo "Enabling aliases definition"
          shopt -s expand_aliases

          echo "Bootstrapping shellx"
          source shellx.sh

          echo "Checking shellx version command"
          shellx version

          echo "Checking shellx info command"
          shellx info
