name: tag-release

on:
  workflow_dispatch:
    inputs:
      version:
        description: Semmantic version to publish e.g. 1.0.0
        required: true

jobs:
  release-tags:
    name: "Release tags"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check version
        id: check
        run: |
          VERSION=${{ inputs.version }}
          if ! [[ "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Version is not in semantic versioning format"
            exit 1
          fi

      - name: Publish tags
        id: tags
        run: |
          VERSION=${{ inputs.version }}

          # e.g: v1.0.0
          PATCH="v$VERSION"
          # e.g: v1.0
          MINOR="v${VERSION%.*}"
          # e.g: v1
          MAJOR="v${VERSION%.*.*}"
         
          git tag "$PATCH"
          git tag -f "$MINOR"
          git tag -f "$MAJOR"
          git push origin -f --tags
